### ISSUE TITLE
New CSS rule height as !important is forbidding css resize

### ISSUE THREAD

**Issue by FredZinelli** [jcubic/jquery.terminal-www#30]
Hello,

In the last release a  css rule has been set to `!important` and it just broke the possibility to offer manual resizing to users through the `resize` css rule : since the `resize` functionality is working by assigning on the fly the height on the element itself, without using the `!important` flag, it's not possible to override the rule coming from the jQuery terminal.

I didn't find the related rule in the file of the repo (looks like it's not up to date). In my browser, it's in `https://cdn.jsdelivr.net/npm/jquery.terminal/css/jquery.terminal.css`, line 840 (the change got published today, apparently) :

```css
@supports (--css: variables) {
    ...
    terminal {
        ...
        height: calc((var(--terminal-line) * var(--rows)) + (var(--padding, 10) * 2px)) !important;
    }
```
I don't have a `--rows` variable defined, but it still applies and is forcing the terminal to resize depending on the number of lines of the content (without limits => none of the other calculations are applying anymore)

Can we get the `!important` removed, please?

Cheers
